### ISSUE TITLE
How to change title?

### ISSUE THREAD

**Issue by webserveis** [msasikanth/ColorSheet#6]

**Comment by cofirazak** [comment]
is there a way to change the "Pick a color" title?

**Comment by webserveis** [comment]
Yes, I already found it adding string reference `pick_a_color`

**Comment by cofirazak** [comment]
"adding string reference pick_a_color" - what you mean by that? 
what is a "string reference pick_a_color" ? 
and where should i add it?

**Comment by msasikanth** [comment]
In your project strings.xml file, you can add this string to set the name of the sheet.
https://github.com/msasikanth/ColorSheet/blob/193fa46568df744efc5dea95dd053165882e1d1b/colorsheet/src/main/res/values/strings.xml#L22
